/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: shu_digital (https://sketchfab.com/shu_digital)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/wooden-board-0667ae18529447f78409611bcae7b3af
title: Wooden board
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cuttingBoard.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -1.22, -1.14]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials.defaultMat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cuttingBoard.glb')
