export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const REGISTER_NEW_USER = "REGISTER_NEW_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const ERROR_WITH_DIALOGUE = "ERROR_WITH_DIALOGUE";
export const USER_ERROR = "USER_ERROR";
export const REMOVE_USER = "REMOVE_USER";
export const TOGGLE_LEFT_TAB = "TOGGLE_LEFT_TAB";
export const RETURN_SINGLE_ITEM = "RETURN_SINGLE_ITEM";
export const TOGGLE_EDIT_STATE = "TOGGLE_EDIT_STATE";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const TRIGGER_MODAL = "TRIGGER_MODAL";
export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT";
export const USER_DELETED_SUCCESS = "USER_DELETED_SUCCESS";
export const USER_DELETED_FAIL = "USER_DELETED_FAIL";
export const USER_UPDATED_SUCCESS = "USER_UPDATED_SUCCESS";
export const USER_UPDATED_FAIL = "USER_UPDATED_FAIL";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const SHOW_ALERT = "SHOW_ALERT";
export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_FAIL = "ALERT_FAIL";
export const HIDE_ALERT = "HIDE_ALERT";
export const RESET_ALERT = "RESET_ALERT";
export const SET_VIEWPORT_DIMENSIONS = "SET_VIEWPORT_DIMENSIONS";
export const SET_LEFT_TAB_ARRAY = "SET_LEFT_TAB_ARRAY";
export const SET_FORM_INPUTS = "SET_FORM_INPUTS";
export const SET_FORM_DATA = "SET_FORM_DATA";
export const GET_ALL_TACO_INGREDIENTS = "GET_ALL_TACO_INGREDIENTS";
export const TACO_ERROR = "TACO_ERROR";
export const ADD_TACO_INGREDIENT = "ADD_TACO_INGREDIENT";
export const SET_NAV_HEIGHT = "SET_NAV_HEIGHT";
export const SHOW_ACCOUNT_MENU = "SHOW_ACCOUNT_MENU";
export const DISPOSE_ACCOUNT_MENU = "DISPOSE_ACCOUNT_MENU";
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const LOGOUT = "LOGOUT";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAIL = "AUTO_LOGIN_FAIL";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const IS_CLIENT = "IS_CLIENT";
export const TOGGLE_SIGNUP_FORM = "TOGGLE_SIGNUP_FORM";
// modal stuff here
export const MODAL_CONFIRMED = "MODAL_CONFIRMED";
export const MODAL_DISMISSED = "MODAL_DISMISSED";
export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_MODAL = "SHOW_MODAL";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const RESET_SNACKBAR = "RESET_SNACKBAR";
export const HIDE_BOOLEAN_SNACKBAR = "HIDE_BOOLEAN_SNACKBAR";
export const SHOW_BOOLEAN_SNACKBAR = "SHOW_BOOLEAN_SNACKBAR";
export const RESET_BOOLEAN_SNACKBAR = "RESET_BOOLEAN_SNACKBAR";

// NETWORK STUFF:
export const IS_LOADING = "IS_LOADING";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const NETWORK_RESPONSE = "NETWORK_RESPONSE";
export const TIMER_START = "TIMER_START";
export const TIMER_END = "TIMER_END";

// RECIPE STUFF:
export const ADD_NEW_RECIPE_SUCCESS = "ADD_NEW_RECIPE_SUCCESS";
export const ADD_NEW_RECIPE_ERROR = "ADD_NEW_RECIPE_ERROR";
export const ADD_NEW_RECIPE = "ADD_NEW_RECIPE";
export const ADD_RECIPE_IMAGE = "ADD_RECIPE_IMAGE";
export const SEND_UPLOAD_PROGRESS = "SEND_UPLOAD_PROGRESS";
export const GET_USER_RECIPES_FAIL = "GET_USER_RECIPES_FAIL";
export const GET_USER_RECIPES_SUCCESS = "GET_USER_RECIPES_SUCCESS";
export const SHOW_ADD_IMAGE_MODAL = "SHOW_ADD_IMAGE_MODAL";
export const DISMISS_ADD_IMAGE_MODAL = "DISMISS_ADD_IMAGE_MODAL";
export const REMOVE_RECIPE_IMAGE = "REMOVE_RECIPE_IMAGE";
export const ADD_RECIPE_IMAGE_ERROR = "ADD_RECIPE_IMAGE_ERROR";
export const REMOVE_RECIPE_SUCCESS = "REMOVE_RECIPE_SUCCESS";
export const REMOVE_RECIPE_ERROR = "REMOVE_RECIPE_ERROR";
export const GET_OWN_RECIPES_SUCCESS = "GET_OWN_RECIPES_SUCCESS";
export const GET_OWN_RECIPES_SERVER = "GET_OWN_RECIPES_SERVER";
export const GET_OWN_RECIPES_ERROR = "GET_OWN_RECIPES_ERROR";

export const RETURN_SINGLE_RECIPE_DETAILS = "RETURN_SINGLE_RECIPE_DETAILS";

// RECIPE FILTER STUFF:
export const ADD_RECIPE_FILTER = "ADD_RECIPE_FILTER";
export const REMOVE_RECIPE_FILTER = "REMOVE_RECIPE_FILTER";
export const CLEAR_RECIPE_FILTERS = "CLEAR_RECIPE_FILTERS";

// RECIPE FAVORITES AND REVIEWS AND SIMILAR SHIT:
export const ADD_RECIPE_FAVORITE = "ADD_RECIPE_FAVORITE";
export const ADD_RECIPE_BOOKMARK = "ADD_RECIPE_BOOKMARK";
export const REMOVE_RECIPE_BOOKMARK = "REMOVE_RECIPE_BOOKMARK";
export const BOOKMARK_ERROR = "BOOKMARK_ERROR";
export const REMOVE_RECIPE_FAVORITE = "REMOVE_RECIPE_FAVORITE";
export const RECIPE_FAVORITE_ERROR = "RECIPE_FAVORITE_ERROR";
export const SHOW_RECIPE_REVIEW_MODAL = "SHOW_RECIPE_REVIEW_MODAL";
export const HIDE_RECIPE_REVIEW_MODAL = "HIDE_RECIPE_REVIEW_MODAL";
export const SUBMIT_RECIPE_REVIEW_SUCCESS = "SUBMIT_RECIPE_REVIEW_SUCCESS";
export const SUBMIT_RECIPE_REVIEW_FAIL = "SUBMIT_RECIPE_REVIEW_FAIL";
